# Generated by Django 2.0.8 on 2018-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180919_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('not-specified', 'Not specified'), ('female', 'Femail'), ('male', 'Male')], max_length=80, null=True),
        ),
    ]
